package nits_ui;


public class AddClientForm extends javax.swing.JDialog {

    private boolean saved = false;

    /**
     * Creates new form AddClientForm
     */
    public AddClientForm(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
}

    public boolean isSaved() {
        return saved;
    }

    public String[] getClientData() {
        return new String[] {
            txtClientID.getText(),
            txtFirstName.getText(),
        txtLastName.getText(),
        txtPhone.getText(),
        txtEmail.getText(),
        txtAddress.getText(),
        txtSSN.getText(),
        (String) sexCombo.getSelectedItem(),
        txtDOB.getText()
    };
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ClientID = new javax.swing.JLabel();
        txtClientID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        Phone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        Sex = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Address1 = new javax.swing.JLabel();
        sexCombo = new javax.swing.JComboBox<>();
        SSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        DOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClientID.setText("ClientID");
        getContentPane().add(ClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 30));

        FirstName.setText("First Name ");
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 30));

        LastName.setText("Last Name");
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 30));

        Phone.setText("Phone");
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 320, 30));

        Email.setText("Email ");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 320, 30));

        Sex.setText("Sex");
        getContentPane().add(Sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 180, -1));

        jButton1.setBackground(new java.awt.Color(0, 151, 178));
        jButton1.setText("Save Client");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 780, 140, 30));

        jButton2.setText("Cancel");
        jButton2.setActionCommand("");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 150, 30));

        Address1.setText("Address ");
        getContentPane().add(Address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 180, -1));

        sexCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sex", "Female", "Male" }));
        getContentPane().add(sexCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 320, 30));

        SSN.setText("SSN");
        getContentPane().add(SSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 180, -1));
        getContentPane().add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 320, 30));

        DOB.setText("DOB");
        getContentPane().add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 180, -1));
        getContentPane().add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saved = true;
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddClientForm dialog = new AddClientForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel ClientID;
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel SSN;
    private javax.swing.JLabel Sex;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> sexCombo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtClientID;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables
}
