package nits_ui;


public class AddPaymentForm extends javax.swing.JDialog {

    private boolean saved = false;

    /**
     * Creates new form AddClientForm
     */
    public AddPaymentForm(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
}

public boolean isSaved() {
    return saved;
}

public String[] getPaymentData() {
    return new String[] {
        txtPaymentID.getText(),
        txtInvoiceID.getText(),
        txtClientID.getText(),  
        txtAmount.getText(),
        (String) methodCombo.getSelectedItem(),
        txtDate.getText()
    };
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PaymentID = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        PaymentMethod = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        methodCombo = new javax.swing.JComboBox<>();
        Amount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        InvoiceID = new javax.swing.JLabel();
        txtInvoiceID = new javax.swing.JTextField();
        ClientID = new javax.swing.JLabel();
        txtClientID = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaymentID.setText("Payment ID");
        getContentPane().add(PaymentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtPaymentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));

        PaymentMethod.setText("Payment Method");
        getContentPane().add(PaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, -1));

        jButton1.setBackground(new java.awt.Color(0, 151, 178));
        jButton1.setText("Save Payment");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 140, 30));

        jButton2.setText("Cancel");
        jButton2.setActionCommand("");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 150, 30));

        methodCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Payment Method", "Card ", "Check", "Cash" }));
        getContentPane().add(methodCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 30));

        Amount.setText("Amount");
        getContentPane().add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 320, 30));

        InvoiceID.setText("Invoice ID");
        getContentPane().add(InvoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));
        getContentPane().add(txtInvoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 30));

        ClientID.setText("Client ID");
        getContentPane().add(ClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));
        getContentPane().add(txtClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 30));

        Date.setText("Date");
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 180, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saved = true;
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddPaymentForm dialog = new AddPaymentForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount;
    private javax.swing.JLabel ClientID;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel InvoiceID;
    private javax.swing.JLabel PaymentID;
    private javax.swing.JLabel PaymentMethod;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> methodCombo;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtClientID;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtInvoiceID;
    private javax.swing.JTextField txtPaymentID;
    // End of variables declaration//GEN-END:variables
}
