package nits_ui;


public class AddServiceForm extends javax.swing.JDialog {

    private boolean saved = false;

    /**
     * Creates new form AddClientForm
     */
    public AddServiceForm(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
}

public boolean isSaved() {
    return saved;
}

public String[] getServiceData() {
    return new String[] {
        txtServiceID.getText(),
        txtServiceName.getText(),
        txtDescription.getText(),
        txtFee.getText()
    };
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ServiceID = new javax.swing.JLabel();
        txtServiceID = new javax.swing.JTextField();
        txtServiceName = new javax.swing.JTextField();
        ServiceName = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        Description = new javax.swing.JLabel();
        txtFee = new javax.swing.JTextField();
        Phone = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ServiceID.setText("Service ID");
        getContentPane().add(ServiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtServiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));
        getContentPane().add(txtServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 30));

        ServiceName.setText("Service Name");
        getContentPane().add(ServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));
        getContentPane().add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 30));

        Description.setText("Description");
        getContentPane().add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));
        getContentPane().add(txtFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 30));

        Phone.setText("Fee");
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));

        jButton1.setBackground(new java.awt.Color(0, 151, 178));
        jButton1.setText("Save Service");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 140, 30));

        jButton2.setText("Cancel");
        jButton2.setActionCommand("");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saved = true;
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddServiceForm dialog = new AddServiceForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel ServiceID;
    private javax.swing.JLabel ServiceName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtFee;
    private javax.swing.JTextField txtServiceID;
    private javax.swing.JTextField txtServiceName;
    // End of variables declaration//GEN-END:variables
}
