package nits_ui;

public class CreateInvoiceForm extends javax.swing.JDialog {

    private Home homeRef;

    public CreateInvoiceForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.homeRef = (Home) parent;

        initComponents();
        loadEngagements();
    }


public String[] getInvoiceData() {
    return new String[] {
    txtInvoiceID.getText(),
    txtEngagementID.getSelectedItem().toString(),
    txtInvoiceDate.getText(),
    txtDueDate.getText(),
    txtStatus.getSelectedItem().toString(),
    txtFinalFee.getText()
};

}


private void loadEngagements() {
    txtEngagementID.removeAllItems();

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) homeRef.getEngagementsTable().getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        Object id = model.getValueAt(i, 0);
        if (id != null) {
            txtEngagementID.addItem(id.toString());
        }
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        InvoiceID = new javax.swing.JLabel();
        txtInvoiceID = new javax.swing.JTextField();
        EngagementID = new javax.swing.JLabel();
        txtInvoiceDate = new javax.swing.JTextField();
        InvoiceDate = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtDueDate = new javax.swing.JTextField();
        DueDate = new javax.swing.JLabel();
        txtFinalFee = new javax.swing.JTextField();
        FinalFee = new javax.swing.JLabel();
        txtStatus = new javax.swing.JComboBox<>();
        txtEngagementID = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InvoiceID.setText("Invoice ID");
        getContentPane().add(InvoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtInvoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));

        EngagementID.setText("Engagement ID");
        getContentPane().add(EngagementID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));
        getContentPane().add(txtInvoiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 320, 30));

        InvoiceDate.setText("Invoice Date");
        getContentPane().add(InvoiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        Status.setText("Status");
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, -1));

        jButton1.setBackground(new java.awt.Color(0, 151, 178));
        jButton1.setText("Create Invoice");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 140, 30));

        jButton2.setText("Cancel");
        jButton2.setActionCommand("");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 150, 30));
        getContentPane().add(txtDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 320, 30));

        DueDate.setText("Due Date");
        getContentPane().add(DueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, -1));
        getContentPane().add(txtFinalFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 320, 30));

        FinalFee.setText("Final Fee");
        getContentPane().add(FinalFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 180, -1));

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Pending", "Paid", "Overdue", "Partial" }));
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 320, 30));
        getContentPane().add(txtEngagementID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateInvoiceForm dialog = new CreateInvoiceForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DueDate;
    private javax.swing.JLabel EngagementID;
    private javax.swing.JLabel FinalFee;
    private javax.swing.JLabel InvoiceDate;
    private javax.swing.JLabel InvoiceID;
    private javax.swing.JLabel Status;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JComboBox<String> txtEngagementID;
    private javax.swing.JTextField txtFinalFee;
    private javax.swing.JTextField txtInvoiceDate;
    private javax.swing.JTextField txtInvoiceID;
    private javax.swing.JComboBox<String> txtStatus;
    // End of variables declaration//GEN-END:variables
}
