package nits_ui;

import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import nits_ui.data.BackendBridge;
import nits_ui.data.RecordOption;


public class CreateEngagementForm extends javax.swing.JDialog {
       
    private boolean saved = false;

    public CreateEngagementForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populateDropdowns();
    }

public boolean isSaved() {
    return saved;
}

public String[] getEngagementData() {
    RecordOption client = (RecordOption) txtClient.getSelectedItem();
    RecordOption service = (RecordOption) txtService1.getSelectedItem();
    RecordOption preparer = (RecordOption) txtPreparer.getSelectedItem();
    return new String[] {
        txtEngagementID.getText(),
        optionIdToString(client),
        optionIdToString(service),
        optionIdToString(preparer),
        txtStartDate.getText(),
        txtExpectedCompletion.getText(),
        txtActualCompletion.getText(),
        txtStatus.getSelectedItem().toString()
    };
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        EngagementID = new javax.swing.JLabel();
        txtEngagementID = new javax.swing.JTextField();
        ClientName = new javax.swing.JLabel();
        Preparer = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        StartDate = new javax.swing.JLabel();
        Service = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtPreparer = new javax.swing.JComboBox<>();
        txtExpectedCompletion = new javax.swing.JTextField();
        ExpectedCompletion = new javax.swing.JLabel();
        txtActualCompletion = new javax.swing.JTextField();
        ActualCompletion = new javax.swing.JLabel();
        txtStatus = new javax.swing.JComboBox<>();
        txtClient = new javax.swing.JComboBox<>();
        txtService1 = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EngagementID.setText("Engagement ID");
        getContentPane().add(EngagementID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtEngagementID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));

        ClientName.setText("Client");
        getContentPane().add(ClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));

        Preparer.setText("Preparer");
        getContentPane().add(Preparer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, -1));
        getContentPane().add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 320, 30));

        StartDate.setText("Start Date");
        getContentPane().add(StartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 180, -1));

        Service.setText("Service");
        getContentPane().add(Service, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        Status.setText("Status");
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 180, -1));

        jButton1.setBackground(new java.awt.Color(0, 151, 178));
        jButton1.setText("Save Engagement");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 710, 140, 30));

        jButton2.setText("Cancel");
        jButton2.setActionCommand("");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 710, 150, 30));

        txtPreparer.addActionListener(this::txtPreparerActionPerformed);
        getContentPane().add(txtPreparer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 320, 30));
        getContentPane().add(txtExpectedCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 320, 30));

        ExpectedCompletion.setText("Expected Completion");
        getContentPane().add(ExpectedCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 180, -1));
        getContentPane().add(txtActualCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 320, 30));

        ActualCompletion.setText("Actual Completion");
        getContentPane().add(ActualCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 180, -1));

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Open", "Ready to File", "Filed", "Closed" }));
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 320, 30));
        getContentPane().add(txtClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 30));

        getContentPane().add(txtService1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saved = true;
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPreparerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreparerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreparerActionPerformed

    private void populateDropdowns() {
        try {
            DefaultComboBoxModel<RecordOption> clientModel =
                    buildModel(BackendBridge.fetchClientOptions());
            DefaultComboBoxModel<RecordOption> serviceModel =
                    buildModel(BackendBridge.fetchServiceOptions());
            DefaultComboBoxModel<RecordOption> employeeModel =
                    buildModel(BackendBridge.fetchEmployeeOptions());

            txtClient.setModel(clientModel);
            txtService1.setModel(serviceModel);
            txtPreparer.setModel(employeeModel);

            if (clientModel.getSize() == 0 || serviceModel.getSize() == 0 || employeeModel.getSize() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Add at least one client, service, and employee before creating an engagement.",
                        "Missing Data",
                        JOptionPane.WARNING_MESSAGE);
                saved = false;
                dispose();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Unable to load engagement options.\n" + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            saved = false;
            dispose();
        }
    }

    private DefaultComboBoxModel<RecordOption> buildModel(List<RecordOption> options) {
        DefaultComboBoxModel<RecordOption> model = new DefaultComboBoxModel<>();
        for (RecordOption option : options) {
            model.addElement(option);
        }
        return model;
    }

    private String optionIdToString(RecordOption option) {
        return option == null ? "" : Integer.toString(option.getId());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateEngagementForm dialog = new CreateEngagementForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualCompletion;
    private javax.swing.JLabel ClientName;
    private javax.swing.JLabel EngagementID;
    private javax.swing.JLabel ExpectedCompletion;
    private javax.swing.JLabel Preparer;
    private javax.swing.JLabel Service;
    private javax.swing.JLabel StartDate;
    private javax.swing.JLabel Status;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField txtActualCompletion;
    private javax.swing.JComboBox<RecordOption> txtClient;
    private javax.swing.JTextField txtEngagementID;
    private javax.swing.JTextField txtExpectedCompletion;
    private javax.swing.JComboBox<RecordOption> txtPreparer;
    private javax.swing.JComboBox<RecordOption> txtService1;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JComboBox<String> txtStatus;
    // End of variables declaration//GEN-END:variables
}
