package nits_ui;


public class CreateAppointmentForm extends javax.swing.JDialog {

    private boolean saved = false;

    /**
     * Creates new form AddClientForm
     */
    public CreateAppointmentForm(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
}

    public boolean isSaved() {
        return saved;
    }

    public String[] getAppointmentData() {
        return new String[] {
            txtAppointmentID.getText(),
        txtClientName.getText(),
        txtEmployeeName.getText(),
        txtDate.getText(),
        txtService.getText(),
        (String) statusCombo.getSelectedItem()
    };
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AppointmentID = new javax.swing.JLabel();
        txtAppointmentID = new javax.swing.JTextField();
        txtClientName = new javax.swing.JTextField();
        ClientName = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        EmployeeName = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        txtService = new javax.swing.JTextField();
        Service = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        statusCombo = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AppointmentID.setText("Appointment ID");
        getContentPane().add(AppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));
        getContentPane().add(txtClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 30));

        ClientName.setText("Client");
        getContentPane().add(ClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));
        getContentPane().add(txtEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 30));

        EmployeeName.setText("Employee");
        getContentPane().add(EmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 30));

        Date.setText("Date");
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));
        getContentPane().add(txtService, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 320, 30));

        Service.setText("Service");
        getContentPane().add(Service, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));

        Status.setText("Status");
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 180, -1));

        jButton1.setBackground(new java.awt.Color(0, 151, 178));
        jButton1.setText("Save Appointment");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 140, 30));

        jButton2.setText("Cancel");
        jButton2.setActionCommand("");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 150, 30));

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Scheduled", "Completed", "Cancelled", "No-Show" }));
        getContentPane().add(statusCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saved = true;
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateAppointmentForm dialog = new CreateAppointmentForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppointmentID;
    private javax.swing.JLabel ClientName;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel EmployeeName;
    private javax.swing.JLabel Service;
    private javax.swing.JLabel Status;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JTextField txtAppointmentID;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtService;
    // End of variables declaration//GEN-END:variables
}
