package nits_ui;

import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import nits_ui.data.BackendBridge;
import nits_ui.data.RecordOption;

public class EditInvoiceForm extends javax.swing.JDialog {

    private int rowIndex = -1;
    private boolean saved = false;

    public EditInvoiceForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populateEngagements(-1);
    }

    public EditInvoiceForm(java.awt.Frame parent, boolean modal,
        int row,
        String invoice_id,
        int engagement_id,
        String invoice_date,
        String due_date,
        String status,
        String final_fee
    ) {
        super(parent, modal);
        initComponents();
        rowIndex = row;
        txtInvoiceID.setText(invoice_id);
        txtInvoiceDate.setText(invoice_date);
        txtDueDate.setText(due_date);
        txtStatus.setSelectedItem(status);
        txtFinalFee.setText(final_fee);
        populateEngagements(engagement_id);
    }

    public String[] getUpdatedData() {
        RecordOption engagement = (RecordOption) txtEngagementID.getSelectedItem();
        return new String[] {
            txtInvoiceID.getText(),
            optionIdToString(engagement),
            txtInvoiceDate.getText(),
            txtDueDate.getText(),
            txtStatus.getSelectedItem().toString(),
            txtFinalFee.getText()
        };
    }

    public boolean isSaved() {
        return saved;
    }






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        InvoiceID = new javax.swing.JLabel();
        txtInvoiceID = new javax.swing.JTextField();
        EngagementID = new javax.swing.JLabel();
        txtInvoiceDate = new javax.swing.JTextField();
        InvoiceDate = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        txtDueDate = new javax.swing.JTextField();
        DueDate = new javax.swing.JLabel();
        txtFinalFee = new javax.swing.JTextField();
        FinalFee = new javax.swing.JLabel();
        txtStatus = new javax.swing.JComboBox<>();
        txtEngagementID = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 151, 178));
        jButton3.setText("Save Appointment");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 140, 30));

        jButton4.setText("Cancel");
        jButton4.setActionCommand("");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 150, 30));

        InvoiceID.setText("Invoice ID");
        getContentPane().add(InvoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtInvoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));

        EngagementID.setText("Engagement ID");
        getContentPane().add(EngagementID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));
        getContentPane().add(txtInvoiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 320, 30));

        InvoiceDate.setText("Invoice Date");
        getContentPane().add(InvoiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        Status.setText("Status");
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, -1));
        getContentPane().add(txtDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 320, 30));

        DueDate.setText("Due Date");
        getContentPane().add(DueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, -1));
        getContentPane().add(txtFinalFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 320, 30));

        FinalFee.setText("Final Fee");
        getContentPane().add(FinalFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 180, -1));

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Pending", "Paid", "Overdue", "Partial" }));
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 320, 30));
        getContentPane().add(txtEngagementID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        saved = true;
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void populateEngagements(int engagementIdToSelect) {
        try {
            List<RecordOption> options = BackendBridge.fetchEngagementOptions();
            DefaultComboBoxModel<RecordOption> model = new DefaultComboBoxModel<>();
            for (RecordOption option : options) {
                model.addElement(option);
            }
            txtEngagementID.setModel(model);

            if (model.getSize() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Create at least one engagement before editing invoices.",
                        "Missing Engagements",
                        JOptionPane.WARNING_MESSAGE);
                saved = false;
                dispose();
                return;
            }

            if (engagementIdToSelect >= 0) {
                for (int i = 0; i < model.getSize(); i++) {
                    RecordOption option = model.getElementAt(i);
                    if (option != null && option.getId() == engagementIdToSelect) {
                        txtEngagementID.setSelectedIndex(i);
                        break;
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Unable to load engagements.\n" + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            saved = false;
            dispose();
        }
    }

    private String optionIdToString(RecordOption option) {
        return option == null ? "" : Integer.toString(option.getId());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditInvoiceForm dialog = new EditInvoiceForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DueDate;
    private javax.swing.JLabel EngagementID;
    private javax.swing.JLabel FinalFee;
    private javax.swing.JLabel InvoiceDate;
    private javax.swing.JLabel InvoiceID;
    private javax.swing.JLabel Status;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JComboBox<RecordOption> txtEngagementID;
    private javax.swing.JTextField txtFinalFee;
    private javax.swing.JTextField txtInvoiceDate;
    private javax.swing.JTextField txtInvoiceID;
    private javax.swing.JComboBox<String> txtStatus;
    // End of variables declaration//GEN-END:variables
}
