package nits_ui;


public class EditServiceForm extends javax.swing.JDialog {

    private int rowIndex = -1;

    public EditServiceForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
  public EditServiceForm(
    java.awt.Frame parent, boolean modal,
    int row,
    String id,
    String name,
    String description,
    String fee
) {
    super(parent, modal);
    initComponents();

    rowIndex = row;

    txtServiceID.setText(id);
    txtServiceName.setText(name);
    txtDescription.setText(description);
    txtFee.setText(fee);
}



   public String[] getUpdatedData() {
    return new String[] {
        txtServiceID.getText(),
        txtServiceName.getText(),
        txtDescription.getText(),
        txtFee.getText()
    };
}






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ServiceID = new javax.swing.JLabel();
        txtServiceID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ServiceName = new javax.swing.JLabel();
        txtServiceName = new javax.swing.JTextField();
        Description = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        Phone = new javax.swing.JLabel();
        txtFee = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ServiceID.setText("Service ID");
        getContentPane().add(ServiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtServiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));

        jButton3.setBackground(new java.awt.Color(0, 151, 178));
        jButton3.setText("Save Service");
        jButton3.setActionCommand("Save Service");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 140, 30));

        jButton4.setText("Cancel");
        jButton4.setActionCommand("");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 150, 30));

        ServiceName.setText("Service Name");
        getContentPane().add(ServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));
        getContentPane().add(txtServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 30));

        Description.setText("Description");
        getContentPane().add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));
        getContentPane().add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 30));

        Phone.setText("Fee");
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));
        getContentPane().add(txtFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditServiceForm dialog = new EditServiceForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel ServiceID;
    private javax.swing.JLabel ServiceName;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtFee;
    private javax.swing.JTextField txtServiceID;
    private javax.swing.JTextField txtServiceName;
    // End of variables declaration//GEN-END:variables
}
