package nits_ui;

public class EditPaymentForm extends javax.swing.JDialog {

    private int rowIndex = -1;

    public EditPaymentForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public EditPaymentForm(
        java.awt.Frame parent, boolean modal, int row,
        String id, String invoice, String client,
        String amount, String method, String date
    ) {
        super(parent, modal);
        initComponents();

        rowIndex = row;

        txtPaymentID.setText(id);
        txtInvoiceID.setText(invoice);
        txtClientID.setText(client);
        txtAmount.setText(amount);
        methodCombo.setSelectedItem(method);
        txtDate.setText(date);
    }

    public String[] getUpdatedData() {
        return new String[] {
            txtPaymentID.getText(),
            txtInvoiceID.getText(),
            txtClientID.getText(),
            txtAmount.getText(),
            methodCombo.getSelectedItem().toString(),
            txtDate.getText()
        };
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PaymentID = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        PaymentMethod = new javax.swing.JLabel();
        methodCombo = new javax.swing.JComboBox<>();
        Amount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        InvoiceID = new javax.swing.JLabel();
        txtInvoiceID = new javax.swing.JTextField();
        ClientID = new javax.swing.JLabel();
        txtClientID = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 151, 178));
        jButton3.setText("Save");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 140, 30));

        jButton4.setText("Cancel");
        jButton4.setActionCommand("");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 150, 30));

        PaymentID.setText("Payment ID");
        getContentPane().add(PaymentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtPaymentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));

        PaymentMethod.setText("Payment Method");
        getContentPane().add(PaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, -1));

        methodCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Payment Method", "Card ", "Check", "Cash" }));
        getContentPane().add(methodCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 30));

        Amount.setText("Amount");
        getContentPane().add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 320, 30));

        InvoiceID.setText("Invoice ID");
        getContentPane().add(InvoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));
        getContentPane().add(txtInvoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 30));

        ClientID.setText("Client ID");
        getContentPane().add(ClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));
        getContentPane().add(txtClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 30));

        Date.setText("Date");
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 180, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditPaymentForm dialog = new EditPaymentForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount;
    private javax.swing.JLabel ClientID;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel InvoiceID;
    private javax.swing.JLabel PaymentID;
    private javax.swing.JLabel PaymentMethod;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> methodCombo;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtClientID;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtInvoiceID;
    private javax.swing.JTextField txtPaymentID;
    // End of variables declaration//GEN-END:variables
}
