package nits_ui;
public class EditDocumentForm extends javax.swing.JDialog {
    private int rowIndex = -1;
    private boolean saved = false;
        public EditDocumentForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

public EditDocumentForm(java.awt.Frame parent, boolean modal,
        int row, String id, String client, String type,
        String date, String notes, String status) {
    super(parent, modal);
    initComponents();

    txtDocumentID.setText(id);
    txtClientID.setText(client);
    documentCombo.setSelectedItem(type);
    txtDate.setText(date);
    txtNotes.setText(notes);
    statusCombo.setSelectedItem(status);

    this.rowIndex = row;
}


public String[] getUpdatedData() {
    return new String[] {
        txtDocumentID.getText(),
        txtClientID.getText(),
        (String) documentCombo.getSelectedItem(),
        txtDate.getText(),
        txtNotes.getText(),
        (String) statusCombo.getSelectedItem()
    };
}

public boolean isSaved() {
    return saved;
}







    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DocumentID = new javax.swing.JLabel();
        txtDocumentID = new javax.swing.JTextField();
        txtClientID = new javax.swing.JTextField();
        ClientID = new javax.swing.JLabel();
        DocumentType = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        txtNotes = new javax.swing.JTextField();
        Notes = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        documentCombo = new javax.swing.JComboBox<>();
        statusCombo = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DocumentID.setText("Document ID");
        getContentPane().add(DocumentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtDocumentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));
        getContentPane().add(txtClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 30));

        ClientID.setText("Client ID");
        getContentPane().add(ClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));

        DocumentType.setText("Document Type");
        getContentPane().add(DocumentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 30));

        Date.setText("Date");
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));
        getContentPane().add(txtNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 320, 30));

        Notes.setText("Notes");
        getContentPane().add(Notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));

        Status.setText("Status");
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 180, -1));

        jButton1.setBackground(new java.awt.Color(0, 151, 178));
        jButton1.setText("Save Changes");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 140, 30));

        jButton2.setText("Cancel");
        jButton2.setActionCommand("");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 150, 30));

        documentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Document Type", "Tax Return", "Identification", "Receipt", "Other" }));
        getContentPane().add(documentCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 30));

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Received", "Pending", "Archived" }));
        getContentPane().add(statusCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saved = true;
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditDocumentForm dialog = new EditDocumentForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientID;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel DocumentID;
    private javax.swing.JLabel DocumentType;
    private javax.swing.JLabel Notes;
    private javax.swing.JLabel Status;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> documentCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JTextField txtClientID;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDocumentID;
    private javax.swing.JTextField txtNotes;
    // End of variables declaration//GEN-END:variables
}
