package nits_ui;


public class EditEmployee extends javax.swing.JDialog {

    private int rowIndex = -1;

    public EditEmployee(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public EditEmployee(java.awt.Frame parent, boolean modal, int row,
        String id, String fn, String ln,
        String phone, String email, String role, String startDate) {

    super(parent, modal);
    initComponents();

    rowIndex = row;

    txtClientID.setText(id);
    txtFirstName.setText(fn);
    txtLastName.setText(ln);
    txtPhone.setText(phone);
    txtEmail.setText(email);
    sexCombo.setSelectedItem(role);
    txtDOB.setText(startDate);
}


    public String[] getUpdatedData() {
    return new String[] {
        txtClientID.getText(),
        txtFirstName.getText(),
        txtLastName.getText(),
        txtPhone.getText(),
        txtEmail.getText(),
        (String) sexCombo.getSelectedItem(),
        txtDOB.getText()
    };
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientID = new javax.swing.JLabel();
        txtClientID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        Phone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        Sex = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sexCombo = new javax.swing.JComboBox<>();
        DOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClientID.setText("EmpID");
        getContentPane().add(ClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 30));

        FirstName.setText("First Name ");
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 30));

        LastName.setText("Last Name");
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 30));

        Phone.setText("Phone");
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 320, 30));

        Email.setText("Email ");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));

        Sex.setText("Role");
        getContentPane().add(Sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 180, -1));

        jButton1.setBackground(new java.awt.Color(0, 151, 178));
        jButton1.setText("Save Employee");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 140, 30));

        jButton2.setText("Cancel");
        jButton2.setActionCommand("");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 150, 30));

        sexCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(sexCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 320, 30));

        DOB.setText("Start Date");
        getContentPane().add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 180, -1));
        getContentPane().add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditEmployee dialog = new EditEmployee(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientID;
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Sex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> sexCombo;
    private javax.swing.JTextField txtClientID;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
