package nits_ui;


public class EditEngagementForm extends javax.swing.JDialog {

    private int rowIndex = -1;

    public EditEngagementForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public EditEngagementForm(
    java.awt.Frame parent, boolean modal,
    int row,
    String id,
    String client,
    String service,
    String preparer,
    String startDate,
    String expected,
    String actual,
    String status
) {
    super(parent, modal);
    initComponents();

    rowIndex = row;

    txtEngagementID.setText(id);
    txtClient.setSelectedItem(client);
    txtService1.setSelectedItem(service);
    txtPreparer.setSelectedItem(preparer);
    txtStartDate.setText(startDate);
    txtExpectedCompletion.setText(expected);
    txtActualCompletion.setText(actual);
    txtStatus.setSelectedItem(status);
}


  public String[] getUpdatedData() {
    return new String[] {
        txtEngagementID.getText(),
        (String) txtClient.getSelectedItem(),
        (String) txtService1.getSelectedItem(),
        (String) txtPreparer.getSelectedItem(),
        txtStartDate.getText(),
        txtExpectedCompletion.getText(),
        txtActualCompletion.getText(),
        (String) txtStatus.getSelectedItem()
    };
}






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        EngagementID = new javax.swing.JLabel();
        txtEngagementID = new javax.swing.JTextField();
        ClientName = new javax.swing.JLabel();
        txtClient = new javax.swing.JComboBox<>();
        Service = new javax.swing.JLabel();
        txtService1 = new javax.swing.JComboBox<>();
        Preparer = new javax.swing.JLabel();
        txtPreparer = new javax.swing.JComboBox<>();
        StartDate = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        ExpectedCompletion = new javax.swing.JLabel();
        txtExpectedCompletion = new javax.swing.JTextField();
        ActualCompletion = new javax.swing.JLabel();
        txtActualCompletion = new javax.swing.JTextField();
        Status = new javax.swing.JLabel();
        txtStatus = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 151, 178));
        jButton3.setText("Save Engagement");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 650, 140, 30));

        jButton4.setText("Cancel");
        jButton4.setActionCommand("");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 150, 30));

        EngagementID.setText("Engagement ID");
        getContentPane().add(EngagementID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));
        getContentPane().add(txtEngagementID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));

        ClientName.setText("Client");
        getContentPane().add(ClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));
        getContentPane().add(txtClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 30));

        Service.setText("Service");
        getContentPane().add(Service, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        getContentPane().add(txtService1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 320, 30));

        Preparer.setText("Preparer");
        getContentPane().add(Preparer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, -1));

        txtPreparer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtPreparer.addActionListener(this::txtPreparerActionPerformed);
        getContentPane().add(txtPreparer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 320, 30));

        StartDate.setText("Start Date");
        getContentPane().add(StartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 180, -1));
        getContentPane().add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 320, 30));

        ExpectedCompletion.setText("Expected Completion");
        getContentPane().add(ExpectedCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 180, -1));
        getContentPane().add(txtExpectedCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 320, 30));

        ActualCompletion.setText("Actual Completion");
        getContentPane().add(ActualCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 180, -1));
        getContentPane().add(txtActualCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 320, 30));

        Status.setText("Status");
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 180, -1));

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Open", "Ready to File", "Filed", "Closed" }));
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtPreparerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreparerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreparerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditEngagementForm dialog = new EditEngagementForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualCompletion;
    private javax.swing.JLabel ClientName;
    private javax.swing.JLabel EngagementID;
    private javax.swing.JLabel ExpectedCompletion;
    private javax.swing.JLabel Preparer;
    private javax.swing.JLabel Service;
    private javax.swing.JLabel StartDate;
    private javax.swing.JLabel Status;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField txtActualCompletion;
    private javax.swing.JComboBox<String> txtClient;
    private javax.swing.JTextField txtEngagementID;
    private javax.swing.JTextField txtExpectedCompletion;
    private javax.swing.JComboBox<String> txtPreparer;
    private javax.swing.JComboBox<String> txtService1;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JComboBox<String> txtStatus;
    // End of variables declaration//GEN-END:variables
}
